version: 2

sources:
  - name: raw_data_circle
    description: raw data circle sportwear from lewagon
    tables:
      - name: raw_cc_stock
        description: stock of products
      - name: raw_cc_sales
        description: sales of products


